export type DivisionType = "animal-healthcare" | "personal-general-care";
export type CategoryGroup = "farm" | "pet" | "poultry" | "floor" | "general";

export interface ProductItem {
  id: string;
  name: string;
  slug: string;
  division: DivisionType;
  divisionLabel: string;
  category: "farm" | "pet" | "poultry" | "hygiene";
  categoryGroup: CategoryGroup;
  categoryLabel: string;
  badge: string;
  badgeBg: string;
  badgeText: string;
  image: string;
  subtitle: string;
  description: string;
  features: string[];
  tags: string[];
  targetAnimals: string;
  keyBenefit: string;
  techTag: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviewsCount: number;
  isPopular?: boolean;
}

export const PRODUCTS: ProductItem[] = [
  // =========================================================================
  // DIVISION 1: ANIMAL HEALTHCARE
  // -------------------------------------------------------------------------
  // SUB-GROUP A: FARM ANIMALS (COW + GOAT)
  // =========================================================================
  {
    id: "prod-farm-1",
    name: "MammaryO Teat Barrier",
    slug: "mammaryo",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "farm",
    categoryGroup: "farm",
    categoryLabel: "Cow & Goat Mastitis Care",
    badge: "Clinical Mastitis Defense",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-800 border-emerald-200",
    image: "/assets/products/mammaryo.jpg",
    subtitle: "Pre- & post-milking teat dip for mastitis prevention in cattle & goats.",
    description: "Clinically tested with TANUVAS-TRPVB. Forms a long-lasting flexible bio-barrier over teat canals, blocking environmental mastitis pathogens (Staphylococcus aureus, E. coli, Streptococcus) while conditioning teat skin with zero milk withholding period.",
    features: ["Clinical Mastitis Infection Control", "Teat Condition & Skin Protection", "Increases Clean Milk Yield"],
    tags: ["farm", "dairy", "mastitis", "udder", "cow", "goat"],
    targetAnimals: "Dairy Cattle, Cows, Goats & Buffaloes",
    keyBenefit: "Saves farmers up to 70% in veterinary antibiotics and lost milk dumping costs.",
    techTag: "Patented Teat Bio-Shield",
    price: 649,
    originalPrice: 899,
    rating: 4.9,
    reviewsCount: 142,
    isPopular: true,
  },
  {
    id: "prod-farm-2",
    name: "AnimaSpray Farm Wound Shield",
    slug: "animaspray-farm",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "farm",
    categoryGroup: "farm",
    categoryLabel: "Cow & Goat Wound Care",
    badge: "Heavy-Duty Bio-Barrier",
    badgeBg: "bg-amber-50",
    badgeText: "text-amber-800 border-amber-200",
    image: "/assets/products/animaspray_farm.jpg",
    subtitle: "Rugged bio-barrier spray for cattle & goat wounds, foot rot & horn trimmings.",
    description: "Delivers an adherent, water-resistant bio-matrix over horn trimmings, foot lesions, and castration incisions, blocking dirt, dung, and maggots without stinging.",
    features: ["Rapid Wound Closure in Herd", "Strong Antibacterial Bio-Shield", "Rain & Mud Resistant"],
    tags: ["farm", "wound", "cow", "goat", "cattle"],
    targetAnimals: "Cows, Goats, Sheep & Herd Animals",
    keyBenefit: "Quiet non-aerosol spray application that does not spook cows or goats.",
    techTag: "Rugged Bio-Film Matrix",
    price: 499,
    originalPrice: 650,
    rating: 4.8,
    reviewsCount: 98,
    isPopular: true,
  },
  {
    id: "prod-farm-3",
    name: "TikiFence Ectoparasite Herd Wash",
    slug: "tikifence",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "farm",
    categoryGroup: "farm",
    categoryLabel: "Cow & Goat Tick Control",
    badge: "Non-Toxic Herd Wash",
    badgeBg: "bg-sky-50",
    badgeText: "text-sky-800 border-sky-200",
    image: "/assets/products/tikifence.jpg",
    subtitle: "High-potency tick & mite repellent wash for cow & goat herds.",
    description: "Eco-friendly tick, mite, lice, and fly repellent shampoo for cows, buffaloes, and goats. Non-neurotoxic, making it 100% safe for lactating animals and milkers.",
    features: ["Aggressive Tick & Mite Repellent", "Lice & Biting Fly Control", "Zero Chemical Milk Residues"],
    tags: ["farm", "tick", "parasite", "cow", "goat"],
    targetAnimals: "Dairy Cows, Goats, Buffaloes & Sheep",
    keyBenefit: "Safe for lactating mothers and young kids/calves; eliminates tick-borne illness naturally.",
    techTag: "Bio-Nano Emulsion",
    price: 529,
    originalPrice: 699,
    rating: 4.9,
    reviewsCount: 112,
    isPopular: true,
  },
  {
    id: "prod-farm-4",
    name: "CapraCattle Teat & Udder Tonic",
    slug: "capracattle-udder-tonic",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "farm",
    categoryGroup: "farm",
    categoryLabel: "Udder Conditioning Emulsion",
    badge: "Anti-Chapping Formula",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-800 border-emerald-200",
    image: "/assets/products/mammaryo.jpg",
    subtitle: "Deep conditioning emollient for high-yield cow & goat teats.",
    description: "Specially formulated for milking cows and dairy goats to prevent cracked teats, hyperkeratosis, and harsh winter chaffing. Enhances tissue elasticity and natural udder defense.",
    features: ["Prevents Teat Chapping & Calluses", "Soothes Milking Machine Stress", "Zero Residue in Raw Milk"],
    tags: ["farm", "udder", "cow", "goat"],
    targetAnimals: "Milking Cows, Dairy Goats & Ewes",
    keyBenefit: "Restores teat skin softness in 48 hours, eliminating milking pain and agitation.",
    techTag: "Phyto-Emollient Bio-Complex",
    price: 449,
    originalPrice: 599,
    rating: 4.8,
    reviewsCount: 79,
    isPopular: false,
  },
  {
    id: "prod-farm-5",
    name: "FarmEnviron Barn Sanitizer",
    slug: "farmenviron",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "farm",
    categoryGroup: "farm",
    categoryLabel: "Shed & Barn Hygiene",
    badge: "Eco-Safe Farm Sanitizer",
    badgeBg: "bg-teal-50",
    badgeText: "text-teal-800 border-teal-200",
    image: "/assets/products/farmenviron.jpg",
    subtitle: "Eco-safe barn & goat shed biofilm disinfectant.",
    description: "Industrial-scale green bio-disinfectant for cattle sheds, goat pens, and milking parlors. Destroys pathogenic biofilms without corrosive chlorine fumes.",
    features: ["100% Farm & Animal-Safe", "Non-Toxic & Biodegradable", "Superior Biofilm Eradication"],
    tags: ["farm", "hygiene", "shed", "cow", "goat"],
    targetAnimals: "Cow Sheds, Goat Pens, Stables & Parlors",
    keyBenefit: "Does not corrode metal stanchions or release harmful chlorine gas in closed sheds.",
    techTag: "Green Bio-Sanitizer",
    price: 899,
    originalPrice: 1199,
    rating: 4.7,
    reviewsCount: 64,
    isPopular: false,
  },

  // =========================================================================
  // SUB-GROUP B: PET ANIMALS (DOG + CAT — 10 PRODUCTS)
  // =========================================================================
  {
    id: "prod-pet-1",
    name: "Anima Spray Pet Wound Care",
    slug: "anima-spray-pet",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Pet Wound Healing",
    badge: "100% Lick-Safe",
    badgeBg: "bg-rose-50",
    badgeText: "text-rose-700 border-rose-200",
    image: "/assets/products/animaspray.jpg",
    subtitle: "Heals dog & cat cuts, abrasions & hot spots faster naturally.",
    description: "Bio-polymer spray that creates a protective breathable film over cuts, surgical incisions, abrasions, hot spots, and open wounds. Accelerates tissue regeneration and is 100% lick-safe.",
    features: ["Rapid Wound Closure", "Broad Antibacterial Barrier", "100% Lick-Safe & Non-Stinging"],
    tags: ["pet", "wound", "dog", "cat", "first-aid"],
    targetAnimals: "Dogs, Cats, Puppies & Kittens",
    keyBenefit: "Forms an instant protective nanobio shield that repels maggots, flies, and dirt.",
    techTag: "Bio-Chitosan Matrix",
    price: 399,
    originalPrice: 550,
    rating: 4.9,
    reviewsCount: 185,
    isPopular: true,
  },
  {
    id: "prod-pet-2",
    name: "PetSha Aloe Vera Shampoo",
    slug: "petsha",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Grooming & Coat",
    badge: "Organic Aloe & Neem",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-700 border-emerald-200",
    image: "/assets/products/petsha.jpg",
    subtitle: "Natural soothing dog & cat conditioning shampoo.",
    description: "Hypoallergenic herbal shampoo infused with pure bio-stabilized aloe vera, neem derivatives, and gentle conditioning agents. Restores skin microbiome balance.",
    features: ["Enriched with Pure Aloe Vera", "Deep Hydrating & Moisturizing", "Silky, Lustrous Coat & Odor-Free"],
    tags: ["pet", "grooming", "shampoo", "dog", "cat"],
    targetAnimals: "All Breeds of Dogs & Cats",
    keyBenefit: "Free from harsh sulfates, parabens, and artificial chemical perfumes.",
    techTag: "Phyto-Biopolymer",
    price: 349,
    originalPrice: 480,
    rating: 4.8,
    reviewsCount: 120,
    isPopular: true,
  },
  {
    id: "prod-pet-3",
    name: "Dermisward Antifungal Spray",
    slug: "dermisward",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Pet Dermatology",
    badge: "Steroid-Free Anti-Itch",
    badgeBg: "bg-amber-50",
    badgeText: "text-amber-800 border-amber-200",
    image: "/assets/products/dermisward.jpg",
    subtitle: "Antifungal & anti-itch natural therapeutic spray for dogs & cats.",
    description: "Steroid-free dermaceutical spray for canine and feline dermatitis, ringworm, yeast infections, malassezia, and chronic paw licking. Relieves itching within minutes.",
    features: ["Stops Chronic Itching & Redness", "Soothes Fungal Irritation", "Gentle, Steroid-Free & Safe"],
    tags: ["pet", "skin", "antifungal", "dog", "cat"],
    targetAnimals: "Dogs, Cats & Small Pets",
    keyBenefit: "Destroys fungal cell membranes naturally without damaging healthy skin flora.",
    techTag: "Bioactive Nanoparticles",
    price: 449,
    originalPrice: 599,
    rating: 4.9,
    reviewsCount: 156,
    isPopular: true,
  },
  {
    id: "prod-pet-4",
    name: "OtoSpray Ear Hygiene Rinse",
    slug: "otospray",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Pet Ear Care",
    badge: "Alcohol-Free Non-Sting",
    badgeBg: "bg-teal-50",
    badgeText: "text-teal-800 border-teal-200",
    image: "/assets/products/otospray.jpg",
    subtitle: "Gentle ear cleanser & microbial rinse for dogs & cats.",
    description: "Non-irritating, non-alcoholic otic rinse formulated with nanobio cleansing agents. Dissolves stubborn cerumen (ear wax), cleanses ear canals, and combats otitis externa.",
    features: ["Gentle Wax & Odor Cleansing", "Soothes Ear Canals & Irritation", "Alcohol-Free & Non-Stinging"],
    tags: ["pet", "ears", "hygiene", "dog", "cat"],
    targetAnimals: "Dogs (especially floppy-eared breeds) & Cats",
    keyBenefit: "No painful stinging or alcohol burn; calms head-shaking and itching instantly.",
    techTag: "Naxpoly® Otic Tech",
    price: 379,
    originalPrice: 499,
    rating: 4.7,
    reviewsCount: 88,
    isPopular: false,
  },
  {
    id: "prod-pet-5",
    name: "Tiksha Botanical Tick Shampoo",
    slug: "tiksha",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Anti-Tick Pet Shampoo",
    badge: "Botanical Defense",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-700 border-emerald-200",
    image: "/assets/products/tiksha.jpg",
    subtitle: "Natural tick & flea protection shampoo for companion pets.",
    description: "Chemical-free botanical shampoo combining fortified natural surfactants with bio-polymers to dislodge ticks and fleas, and create a lasting defensive scent barrier.",
    features: ["Natural Tick & Flea Defense", "Gentle, Skin-Friendly Formula", "Prevents Re-Infestation"],
    tags: ["pet", "tick", "grooming", "dog", "cat"],
    targetAnimals: "Dogs & Cats of all ages",
    keyBenefit: "Non-neurotoxic; safe for children to cuddle pets immediately after drying.",
    techTag: "Botanical Nano-Complex",
    price: 369,
    originalPrice: 499,
    rating: 4.8,
    reviewsCount: 94,
    isPopular: false,
  },
  {
    id: "prod-pet-6",
    name: "PetDent Oral Hygiene Spray",
    slug: "petdent",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Oral & Dental Care",
    badge: "Fresh Breath Enzyme",
    badgeBg: "bg-cyan-50",
    badgeText: "text-cyan-800 border-cyan-200",
    image: "/assets/products/PE 3.jpeg",
    subtitle: "No-brushing enzyme dental spray for dog & cat breath & tartar.",
    description: "Gentle oral spray that breaks down food biofilms, dissolves tartar accumulation, and prevents gingivitis. Freshens dog and cat breath effortlessly without toothbrushes.",
    features: ["Dissolves Plaque & Tartar", "Eliminates Foul Pet Breath", "No-Brush Easy Daily Mist"],
    tags: ["pet", "dental", "oral", "dog", "cat"],
    targetAnimals: "Dogs, Cats, Puppies & Kittens",
    keyBenefit: "Spray directly onto teeth or drinking water; neutral taste pets accept easily.",
    techTag: "Bio-Enzymatic Cleanse",
    price: 389,
    originalPrice: 520,
    rating: 4.8,
    reviewsCount: 68,
    isPopular: false,
  },
  {
    id: "prod-pet-7",
    name: "PawShield Protective Paw Balm & Mist",
    slug: "pawshield",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Paw & Snout Care",
    badge: "100% Lick-Safe Wax",
    badgeBg: "bg-orange-50",
    badgeText: "text-orange-800 border-orange-200",
    image: "/assets/products/Anima 3.jpeg",
    subtitle: "Protective soothing barrier for cracked paws & dry snouts.",
    description: "Organic beeswax and nano-emollient blend designed to protect paws against hot pavement, coarse gravel, and harsh weather. Deeply moisturizes dry, cracked nose leathers.",
    features: ["Shields Against Hot Pavements", "Heals Cracked, Dry Paws", "Rapid Absorption & Lick-Safe"],
    tags: ["pet", "paws", "dog", "cat"],
    targetAnimals: "Dogs & Cats of all breeds",
    keyBenefit: "Non-greasy bio-wax formula will not leave slippery stains on hardwood floors.",
    techTag: "Botanical Nano-Wax",
    price: 329,
    originalPrice: 450,
    rating: 4.9,
    reviewsCount: 104,
    isPopular: false,
  },
  {
    id: "prod-pet-8",
    name: "EyeCare Tear-Stain & Soothing Eye Rinse",
    slug: "eyecare-rinse",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Ophthalmic Hygiene",
    badge: "Isotonic Herbal Wash",
    badgeBg: "bg-blue-50",
    badgeText: "text-blue-800 border-blue-200",
    image: "/assets/products/otospray.jpg",
    subtitle: "Gentle eye flusher & tear stain remover for dogs & cats.",
    description: "Sterile, isotonic saline solution enriched with natural euphrasia and chamomile extracts. Flushes pollen, dirt, and discharge while progressively fading reddish tear stains.",
    features: ["Flushes Dust, Pollen & Mucus", "Clears Unsightly Tear Stains", "Non-Stinging Neutral pH"],
    tags: ["pet", "eyes", "tear-stain", "dog", "cat"],
    targetAnimals: "Dogs (Shih Tzu, Poodle, Pug) & Cats (Persian)",
    keyBenefit: "Matches natural tear pH exactly to avoid irritation or eye squinting.",
    techTag: "Isotonic Bio-Rinse",
    price: 359,
    originalPrice: 479,
    rating: 4.7,
    reviewsCount: 52,
    isPopular: false,
  },
  {
    id: "prod-pet-9",
    name: "FurGlow Silk Protein Coat Serum",
    slug: "furglow-serum",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Coat & Anti-Shedding",
    badge: "Hydrolyzed Silk Protein",
    badgeBg: "bg-purple-50",
    badgeText: "text-purple-800 border-purple-200",
    image: "/assets/products/petsha.jpg",
    subtitle: "Leave-in coat revitalizer & anti-shedding serum for dogs & cats.",
    description: "Enriched with plant-derived silk proteins, Omega-3 fatty acid nano-emulsions, and vitamin E. Detangles mats, reduces seasonal shedding, and imparts a glossy exhibition shine.",
    features: ["Reduces Excessive Shedding", "Detangles Mats & Knots Easily", "Silky Gloss & Fresh Scent"],
    tags: ["pet", "coat", "grooming", "dog", "cat"],
    targetAnimals: "Long-Haired & Short-Haired Dogs & Cats",
    keyBenefit: "Zero silicone build-up; keeps the undercoat light, airy, and tangle-free.",
    techTag: "Silk Peptide Nano-Serum",
    price: 469,
    originalPrice: 620,
    rating: 4.9,
    reviewsCount: 118,
    isPopular: false,
  },
  {
    id: "prod-pet-10",
    name: "FleaGo Herbal Spot-On Shield Drops",
    slug: "fleago-spot-on",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "pet",
    categoryGroup: "pet",
    categoryLabel: "Natural Spot-On Defense",
    badge: "Fipronil-Free Botanical",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-800 border-emerald-200",
    image: "/assets/products/Dermi 2.jpeg",
    subtitle: "Monthly plant-based spot-on repellent for fleas, ticks & mites.",
    description: "Gentle topical drops applied between the shoulder blades. Naturally diffuses across skin sebum to deter fleas, ticks, and mosquitoes for up to 30 days without toxic synthetic pesticides.",
    features: ["30-Day Tick & Flea Protection", "100% Free of Neurotoxins", "Safe Around Kids & Other Pets"],
    tags: ["pet", "flea", "tick", "dog", "cat"],
    targetAnimals: "Puppies, Kittens, Adult Dogs & Cats",
    keyBenefit: "No dangerous chemical pesticide side-effects; ideal for sensitive or allergic pets.",
    techTag: "Botanical Micro-Encapsulation",
    price: 499,
    originalPrice: 699,
    rating: 4.8,
    reviewsCount: 87,
    isPopular: true,
  },

  // =========================================================================
  // SUB-GROUP C: POULTRY / BIRDS (3 PRODUCTS)
  // =========================================================================
  {
    id: "prod-poultry-1",
    name: "FarmSward Poultry Flock Defense",
    slug: "farmsward",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "poultry",
    categoryGroup: "poultry",
    categoryLabel: "Flock Immunity & Misting",
    badge: "Flock Immune Shield",
    badgeBg: "bg-blue-50",
    badgeText: "text-blue-800 border-blue-200",
    image: "/assets/products/farmsward.jpg",
    subtitle: "Flock defense & natural avian biosecurity mist for commercial sheds.",
    description: "Bio-protective water and misting formulation designed to curb avian respiratory bacteria, improve flock biosecurity, and minimize broiler mortality without synthetic antibiotics.",
    features: ["Flock Antibacterial Defense", "Enhanced Bio-Performance", "Supports Higher FCR & Egg Yield"],
    tags: ["poultry", "birds", "farm", "hygiene"],
    targetAnimals: "Broilers, Layers, Breeders, Ducks & Hatcheries",
    keyBenefit: "Helps commercial poultry producers achieve export-grade Antibiotic-Free (ABF) certification.",
    techTag: "Avian Shield Tech",
    price: 799,
    originalPrice: 1099,
    rating: 4.8,
    reviewsCount: 76,
    isPopular: true,
  },
  {
    id: "prod-poultry-2",
    name: "AvioPure Drinking Line Water Sanitizer",
    slug: "aviopure-water-sanitizer",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "poultry",
    categoryGroup: "poultry",
    categoryLabel: "Poultry Water Sanitizer",
    badge: "Biofilm Eradication",
    badgeBg: "bg-cyan-50",
    badgeText: "text-cyan-800 border-cyan-200",
    image: "/assets/products/farmsward.jpg",
    subtitle: "Continuous water line biofilm & gut hygiene sanitizer for birds.",
    description: "Stabilized green water sanitizer that cleans poultry nipple drinker lines, eliminates microbial biofilm, and enhances chick gut microbial integrity without affecting vaccine efficacy.",
    features: ["Clears Drinker Line Biofilms", "Curbs E. coli & Salmonella Risks", "Improves Water Intake & Gut Health"],
    tags: ["poultry", "birds", "water", "hygiene"],
    targetAnimals: "Poultry Farms, Aviaries & Game Birds",
    keyBenefit: "Non-corrosive to plastic drinker nipples; neutralizes heavy water slime safely.",
    techTag: "Green Biofilm Dissolver",
    price: 699,
    originalPrice: 950,
    rating: 4.9,
    reviewsCount: 62,
    isPopular: false,
  },
  {
    id: "prod-poultry-3",
    name: "AvianHeal Peck & Wound Shield Spray",
    slug: "avianheal-peck-spray",
    division: "animal-healthcare",
    divisionLabel: "Animal Healthcare",
    category: "poultry",
    categoryGroup: "poultry",
    categoryLabel: "Avian Wound & Peck Care",
    badge: "Anti-Cannibalism Bio-Dye",
    badgeBg: "bg-amber-50",
    badgeText: "text-amber-800 border-amber-200",
    image: "/assets/products/animaspray.jpg",
    subtitle: "Protective wound barrier & anti-feather pecking recovery spray.",
    description: "Rapidly seals flesh wounds caused by cannibalistic feather pecking, predator scratches, or cage snags. Contains natural bitter bio-extracts that deter other birds from repeated pecking.",
    features: ["Deters Further Feather Pecking", "Fast Scab & Tissue Recovery", "Non-Stinging Antiseptic"],
    tags: ["poultry", "birds", "wound", "first-aid"],
    targetAnimals: "Chickens, Turkeys, Quails & Aviary Birds",
    keyBenefit: "Stops flock cannibalism in its tracks while disinfecting injured tissues.",
    techTag: "Bio-Peck Repel Matrix",
    price: 429,
    originalPrice: 580,
    rating: 4.7,
    reviewsCount: 45,
    isPopular: false,
  },

  // =========================================================================
  // DIVISION 2: PERSONAL / GENERAL CARE
  // -------------------------------------------------------------------------
  // SUB-GROUP A: FLOOR CLEANER
  // =========================================================================
  {
    id: "prod-care-1",
    name: "Cleanida Eco Floor Cleaner",
    slug: "cleanida",
    division: "personal-general-care",
    divisionLabel: "Personal / General Care",
    category: "hygiene",
    categoryGroup: "floor",
    categoryLabel: "Floor Cleaner",
    badge: "100% Chemical Free",
    badgeBg: "bg-teal-50",
    badgeText: "text-teal-800 border-teal-200",
    image: "/assets/products/cleanida.jpg",
    subtitle: "Probiotic multi-surface floor sanitizer for homes with pets & families.",
    description: "Probiotic and nano-bio multi-surface floor cleaner for homes with pets, vet hospitals, and animal shelters. Neutralizes pet odors and urine pheromones naturally.",
    features: ["Hospital-Grade Floor Disinfection", "Child & Pet Safe When Wet or Dry", "Eco-Friendly & Hypoallergenic"],
    tags: ["hygiene", "floor", "eco", "cleaner", "general"],
    targetAnimals: "Homes, Kennels, Veterinary Clinics & Animal Cages",
    keyBenefit: "Zero toxic synthetic chemicals; safe for bare human feet and curious pet tongues.",
    techTag: "Eco-Pure Enzyme Formula",
    price: 349,
    originalPrice: 450,
    rating: 4.8,
    reviewsCount: 88,
    isPopular: true,
  },

  // =========================================================================
  // SUB-GROUP B: OTHER 2–3 GENERAL CARE PRODUCTS
  // =========================================================================
  {
    id: "prod-care-2",
    name: "PetEnviron Surface Disinfectant",
    slug: "petenviron",
    division: "personal-general-care",
    divisionLabel: "Personal / General Care",
    category: "hygiene",
    categoryGroup: "general",
    categoryLabel: "Clinic & Multi-Surface Disinfectant",
    badge: "Broad-Spectrum Bio-Guard",
    badgeBg: "bg-indigo-50",
    badgeText: "text-indigo-700 border-indigo-200",
    image: "/assets/products/petenviron.jpg",
    subtitle: "Pet safe multi-surface environmental disinfectant for clinics & households.",
    description: "Broad-spectrum nanobio polymer surface disinfectant specially engineered for animal shelters, veterinary clinics, grooming salons, and pet homes.",
    features: ["Antibacterial & Antiviral Defense", "Broad Antifungal Action", "100% Biodegradable & Non-Toxic"],
    tags: ["hygiene", "surface", "disinfectant", "general"],
    targetAnimals: "Veterinary Clinics, Kennels, Cages & Countertops",
    keyBenefit: "Zero toxic bleach residues; safe for pet skin contact immediately upon drying.",
    techTag: "Naxpoly® Bio-Barrier",
    price: 499,
    originalPrice: 650,
    rating: 4.9,
    reviewsCount: 130,
    isPopular: false,
  },
  {
    id: "prod-care-3",
    name: "OdorFree Natural Pet Odor & Stain Eliminator",
    slug: "odorfree-stain-eliminator",
    division: "personal-general-care",
    divisionLabel: "Personal / General Care",
    category: "hygiene",
    categoryGroup: "general",
    categoryLabel: "Enzymatic Odor Destroyer",
    badge: "Pheromone Neutralizer",
    badgeBg: "bg-rose-50",
    badgeText: "text-rose-800 border-rose-200",
    image: "/assets/products/cleanida.jpg",
    subtitle: "Instant enzymatic urine, litter box & vomit odor neutralizer.",
    description: "Bioactive enzymatic spray that penetrates deep into rugs, sofas, car seats, and litter boxes to permanently break down uric acid crystals and territorial marking scents.",
    features: ["Permanently Destroys Uric Acid", "Stops Repeated Territorial Marking", "Fresh Herbal Citrus Essence"],
    tags: ["hygiene", "odor", "stain", "general"],
    targetAnimals: "Carpets, Sofas, Litter Trays & Pet Bedding",
    keyBenefit: "Does not simply mask smells; permanently consumes biological odor molecules.",
    techTag: "Bio-Enzymatic Digestant",
    price: 379,
    originalPrice: 499,
    rating: 4.8,
    reviewsCount: 92,
    isPopular: false,
  },
  {
    id: "prod-care-4",
    name: "PureHands Bio-Defense Hand Wash",
    slug: "purehands-handwash",
    division: "personal-general-care",
    divisionLabel: "Personal / General Care",
    category: "hygiene",
    categoryGroup: "general",
    categoryLabel: "Milker & Pet Parent Hand Wash",
    badge: "Zero-Alcohol Gentle Guard",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-800 border-emerald-200",
    image: "/assets/products/PE 3.jpeg",
    subtitle: "Antibacterial moisturising hand defense for dairy milkers & pet owners.",
    description: "Specially formulated for dairy farmers before and after milking, and pet lovers handling medications. Non-drying, alcohol-free bio-polymer hand cleanser that prevents cross-contamination.",
    features: ["Prevents Cross-Herd Microbial Transfer", "Deeply Moisturizes Chapped Hands", "Alcohol-Free & 100% Food-Grade"],
    tags: ["personal", "hygiene", "handwash", "general"],
    targetAnimals: "Dairy Milkers, Vet Staff & Pet Parents",
    keyBenefit: "Protects farmer hands against rough fissures while keeping cow teats sterile.",
    techTag: "Dermal Bio-Armor",
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviewsCount: 61,
    isPopular: false,
  },
];
